### ISSUE TITLE
[FEATURE REQUEST] Expose reset transform/translate trigger in v-zoomer-gallery

### ISSUE THREAD

**Issue by CesarGomezTissini** [jarvisniu/vue-zoomer#1]
Some situation when we use vue-zoomer from a Dialog (v-dialog from Vuetify), it's necessary reset transform/translate values in zoomed image. I know there is a zoomed event, but this is not enough.

According [your code](https://github.com/jarvisniu/vue-zoomer/commit/19ddf539f5ceb4c870855a95571b60827d7d4e40#diff-6014de761afc760c1baeebd42a825f56R81), there is too a trigger to reset transform/translate zoomed image. I wanna use when I press close in dialog.

**Comment by jarvisniu** [comment]
Oh, there is also a [`reset()` method](https://github.com/jarvisniu/vue-zoomer/blob/19ddf539f5ceb4c870855a95571b60827d7d4e40/src/vue-zoomer.vue#L172). Are you looking for this?

**Comment by CesarGomezTissini** [comment]
```html
<v-zoomer-gallery
     ref="galleryZoom"
     v-model="selIndex"
     style="width: 80vw; height: 400px"
     :list="gallery">
</v-zoomer-gallery>
```

```javascript
this.$refs.galleryZoom.reset()
```

> Error in v-on handler: "TypeError: this.$refs.galleryZoom.reset is not a function"

That's why my proposal. `v-zoomer-gallery` doesn't have that method.

**Comment by jarvisniu** [comment]
Sorry for misunderstanding it. I have added the `reset` method to `v-zoomer-gallery`. Please update to the newest v0.2.9 version.
