### ISSUE TITLE
Image zoom with cursor pivot zooms always far to the right of the cursor

### ISSUE THREAD

**Issue by alejandroiglesias** [jarvisniu/vue-zoomer#11]
The cursor position seems to be incorrectly detected because the image always zooms in to the far right of the cursor. Please let me know if you need more information.

**Comment by jarvisniu** [comment]
Yes, this bug exists indeed. Thanks to point it out.
I have fixed it now. Please upgrade to `v0.3.6` and have a try.

**Comment by alejandroiglesias** [comment]
I've tested the new version and now the image zooms in to the far left of the cursor.

**Comment by jarvisniu** [comment]
I have fixed a bug in `v0.3.8` that may also related to this issue. You can try if it still exists now.
If it is. Please tell me the procedures to reproduce it, thank you!
