### ISSUE TITLE
Zoom center issue

### ISSUE THREAD

**Issue by Somosmosaicdesign** [jarvisniu/vue-zoomer#2]
Hello,  I tried your module and it works great but when zooming the image translate strangely as it tried to center around the middle of the image. it is strange for the users, they expect the image to stay centered on the mouse pointer. Do you have an idea how to fix it ?

regards

**Comment by jarvisniu** [comment]
I have added a prop `noTranslateLimit` to solve your problem, you can update to `v0.2.11` and use it like:
```diff
    <v-zoomer
+     no-translate-limit
    >
      <img src="../assets/landscape-1.jpg">
    </v-zoomer>
```
or
```diff
    <v-zoomer-gallery
      :list="urlImageList"
      v-model="selIndex"
+     no-translate-limit
    ></v-zoomer-gallery>
```

**Comment by jarvisniu** [comment]
I looked at your forked code and found that I misunderstand your intention. Sorry for that!
I have added another prop `pivot` for that. The default value is `cursor`, you should set it to `image-center`:
```diff
    <v-zoomer-gallery
      :list="urlImageList"
      v-model="selIndex"
+     pivot="image-center"
    ></v-zoomer-gallery>
```
PS: You should update to `v0.3.0`
