### ISSUE TITLE
Gallery - Once you come back to the previous image then the zoom in/out functionality is not working

### ISSUE THREAD

**Issue by umeshgupta1** [jarvisniu/vue-zoomer#21]

**Comment by rantuma** [comment]
Can you please provide some reproducible code? 
https://www.propublica.org/nerds/how-to-ask-programming-questions

**Comment by umeshgupta1** [comment]
same issue with the gallery demo link - https://unpkg.com/vue-zoomer@0.3.7/dist/demo/gallery.html

video link for ref.
https://www.awesomescreenshot.com/video/2184443?key=24c8c19edf4900e076a2a0b22b2a1ed3

**Comment by jarvisniu** [comment]
OK, I get it. Thank you.
I will try to fix it in next fews days.

**Comment by jarvisniu** [comment]
This bug has been fixed. Thank you guys!
See: https://unpkg.com/vue-zoomer@0.3.8/dist/demo/gallery.html
