### ISSUE TITLE
Feature request: option to disable zoom on mousewheel

### ISSUE THREAD

**Issue by Torone** [jarvisniu/vue-zoomer#22]
As per title... There is not an option to prevent zoom on mousewheel... this should be really easy and quick to add.

**Comment by jarvisniu** [comment]
OK, I will do it tonight.
Thank you for your feedback!

**Comment by jarvisniu** [comment]
Now, the prop `mouseWheelToZoom` is added to version `0.3.7`

**Comment by Torone** [comment]
Cheers for that! Very useful!
