### ISSUE TITLE
Emit is not declared

### ISSUE THREAD

**Issue by schmeiger** [jarvisniu/vue-zoomer#25]
Hey,

I was really happy to find your component to use in my project, but I faced two issues. First of one is that there is no emits declared in your code... That's why in Vue 3 it constantly screams with a warning

![image](https://user-images.githubusercontent.com/4469788/110135700-1d682980-7dcf-11eb-90fc-2631076145fe.png)

https://v3.vuejs.org/guide/migration/emits-option.html#_2-x-behavior

Secondly, I really don't understand how I can use zoomIn and zoomOut methods or some other similar behaviour, where I could detect that the image was zoomed in.

Is there any chance that you provide some little demo for single image use? Like here, but that your JS code would be visible?
https://unpkg.com/vue-zoomer@0.3.9/dist/demo/basic.html

Thank you, in advance! :)

**Comment by schmeiger** [comment]
Ah yeah, I'm most interested in this prop here and what do you mean with sync... Any example how it will look like in code?

![image](https://user-images.githubusercontent.com/4469788/110136973-9caa2d00-7dd0-11eb-826e-1314351509ee.png)

**Comment by schmeiger** [comment]
Hey,

I've figured it out, why it was not working with .sync... 

https://v3.vuejs.org/guide/migration/v-model.html#overview

So I've changed :zoomed.sync to v-model. And it works:
`<v-zoomer ref="zoomer" style="width: 100%; height: 100%;" v-model:zoomed="zoomed" :zooming-elastic="false">
        <img :src="slide.src" :alt="slide.label" />
</v-zoomer>`

The only thing that is missing now in your module is emits declaration:
`emits: ['update:zoomed'],`

One will get rid of the nasty vue warnings... :)
Hope for this update soon ;)

**Comment by schmeiger** [comment]
Oh... by using v-model... I've lost `@click="$refs.zoomer.zoomIn()"` zoomIn/zoomOut functionality... why is that? Some hewp? :)

**Comment by jarvisniu** [comment]
It seems that you are using Vue 3, but the stable version is for Vue 2.

Make sure you have install the Vue 3 version by `npm install vue-zoomer@next` firstly.

Docs here: https://github.com/jarvisniu/vue-zoomer/tree/next
