### ISSUE TITLE
Using any relative height / width doesn't work as intended

### ISSUE THREAD

**Issue by leo91000** [jarvisniu/vue-zoomer#28]
Vue zoomer tries to get width and height using [parseFloat](https://github.com/jarvisniu/vue-zoomer/blob/001bda5c1eb82b3b4a13bf3ca70d5ad1243ceb45/src/vue-zoomer.vue#L236) However sometime we have different setup, for instance :
- We can use `100%`, which parseFloat will parse as `100`. In this case everything will be offseted and zoom won't happen on cursor.
- We can use some advanced css like `calc(100vh - 200px)`. In this case VueZoomer will not work at all. For a quick fix, check if value `isNaN`.

This is why I would suggest to use the [ResizeObserver ](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver)api instead, where you can get exact height and width in pixel, and watch for change of these. 

There is an [example ](https://github.com/vueuse/vueuse/blob/main/packages/core/useResizeObserver/index.ts) in the vue use library.

Would it be possible to implement these change ?

**Comment by jarvisniu** [comment]
I think this issue should not exists, bacause there is a `getComputedStyle` before `parseFloat`:

```js
let styles = window.getComputedStyle(this.$el)
this.containerWidth = parseFloat(styles.width)
```

So, `100%` and `calc(100vh - 200px)` will be converted to the actual size.

**Comment by leo91000** [comment]
Yes indeed, I think my issue is elsewhere. I will try to make a minimal reproducible example if I find some time.

Sorry for the bad call.

**Comment by jarvisniu** [comment]
No problem at all!

If you use Firefox, this may be a compatibility issue:
> During CSS transitions, getComputedStyle returns the original property value in Firefox, but the final property value in WebKit.

See: https://developer.mozilla.org/en-US/docs/Web/API/Window/getComputedStyle#notes

**Comment by leo91000** [comment]
Ah this is probably that thank you !
