### ISSUE TITLE
Support Apple Magic Trackpad and Magic Mouse

### ISSUE THREAD

**Issue by UIX-Design** [jarvisniu/vue-zoomer#3]
Hi, thank you very much for this component. 

I am using the Apple Magic Trackpad or Magic Mouse. It would be very nice, when i could use the swipe-gesture on my trackpad to switch between the images. 

Is it possible to implement that?
If that's too elaborate ... Would it otherwise be possible to display arrows for the gallery navigation on desktop devices?

Another question, it is possible to add properties for image description? I would like to add description above each image, e.g. in the Gallery.

And it is possible to show all images in the gallery as previewImage like that?

![49B7E6C4-4292-4D2B-B7E2-E373066EDFC2](https://user-images.githubusercontent.com/48715009/59536516-34c4fc00-8ef4-11e9-90d6-4839c896c904.png)

**Comment by jarvisniu** [comment]
I have added the swipe gesture on trackpad (updated to `v0.3.1`). But it has a small limit that you can't swipe too frequently because of the momentum of trackpad.

The other 3 questions (navigation arrows, image description, thumbnail list) will not included in the component. Because almost eveyone's desirable ui style is different and they are very easy to implement by themeselves outside the component.

If you have trouble doing it yourself, I can give you some demo code.

**Comment by UIX-Design** [comment]
@jarvisniu thank you very much for that

Thank You, but I was able to implement the functions myself 😉

When i install the version `v0.3.1` via npm i get a warning, after installation:
`Critical dependency: the request of a dependency is an expression` Is that normal?

<img width="375" alt="Bildschirmfoto 2019-06-15 um 10 59 49" src="https://user-images.githubusercontent.com/48715009/59549374-d08a5280-8f5c-11e9-91e3-37c39168373a.png">

When i set `ssr: true` so i don't get the red error, but the other warning is still exists (i am using nuxt 
js)

## Image Display Bug

And another bug i found. When i open the `v-zoom-gallery` it looks like this:

<img width="1516" alt="Bildschirmfoto 2019-06-15 um 11 18 31" src="https://user-images.githubusercontent.com/48715009/59549534-68893b80-8f5f-11e9-8db3-e024459aeb94.png">

After i resizing my screen a little bit, it looks good:

<img width="1507" alt="Bildschirmfoto 2019-06-15 um 11 19 02" src="https://user-images.githubusercontent.com/48715009/59549544-a1291500-8f5f-11e9-8148-a79a08d529d0.png">

Why does this bug occur? Is it a CSS error?

**Comment by jarvisniu** [comment]
You can ignore the warning `the request of a dependency is an expression`. There is no influence actually. This is caused by the UMD module format.

But when you use bundlers (like nuxt), you can fix the warning by replacing:
```js
import VueZoomer from 'vue-zoomer'
import 'vue-zoomer/dist/vue-zoomer.css'
```
with:
```js
import VueZoomer from 'vue-zoomer/src/index.js'
```

**Comment by jarvisniu** [comment]
I have never met the display bug before. If you can find the operation steps to 100% reoccuring. It will be easier to find the bug and fix it.

**Comment by UIX-Design** [comment]
@jarvisniu I honestly have difficulty finding and fixing the display error. I created a demo project on codesandbox.io. Could you please take a look at the code? You may be able to find the bug right away. On first loading, i could see the display bug. But then no more. But maybe you can reconstruct the bug after all. 

I would really be very happy about your support. Thank you very much

https://codesandbox.io/embed/codesandbox-nuxt-3fgie?fontsize=14

I think the problem is because of the slider divs. As you can see on the screen below, the div doesn't go over the full width of the screen. It looks different on your demo page. The slider divs go over the entire screen width

<img width="1472" alt="Bildschirmfoto 2019-06-16 um 21 19 04" src="https://user-images.githubusercontent.com/48715009/59568584-e2631700-907c-11e9-9947-86a301799f3d.png">

After i resizing my screen a little bit, it looks like this:

<img width="1472" alt="Bildschirmfoto 2019-06-16 um 21 24 02" src="https://user-images.githubusercontent.com/48715009/59568598-31a94780-907d-11e9-8206-61f344490b29.png">
The `left` property on the div is now right

**Comment by jarvisniu** [comment]
You can try the following four methods one by one.
If one of these works, I can wrap it into the component.
```diff
  <v-zoomer-gallery
+   ref="zoomer"
    style="width: 100%; height: 100%; background-color: none"
    :list="imageSources"
    v-model="selIndex"
  ></v-zoomer-gallery>

  mounted () {
+   this.$refs.zoomer.onWindowResize() // 1. directly call
+   this.$nextTick(this.$refs.zoomer.onWindowResize) // 2. nextTick
+   setTimeout(this.$refs.zoomer.onWindowResize, 0) // 3. setTimeout-0
+   setTimeout(this.$refs.zoomer.onWindowResize, 100) // 4. setTimeout-100
  },
```

**Comment by UIX-Design** [comment]
@jarvisniu Unfortunately, no method works. The error still exists. What I noticed: When the gallery is opened for the first time, the `left` property is set to `100px` or `-100px`. Only after I have enlarged or shrunk my window do the left properties change to the right values, as you can see on the upper screenshots. Then when I close the gallery and open everything looks great. 

So as it seems it can't access the screen width on first opening or reloading the page, unless I change the width of Chrome

How can we fix this bug? I really want to use your Component

**Comment by jarvisniu** [comment]
Oh, sorry. For your situation, you should add it here:
```diff
openFullscreen() {
  this.fullscreen = true;
+ // this.$nextTick(this.$refs.zoomer.onWindowResize) // 1. nextTick
+ // setTimeout(this.$refs.zoomer.onWindowResize, 0) // 2. setTimeout-0
+ // setTimeout(this.$refs.zoomer.onWindowResize, 100) // 3. setTimeout-100
},
```
Have another try please.

**Comment by UIX-Design** [comment]
@jarvisniu thank you very much, it works now 🎉👍
