### ISSUE TITLE
Support - Pinch zooming on mobile devices forces browser zoom

### ISSUE THREAD

**Issue by alexwahlandt** [jarvisniu/vue-zoomer#30]
Hi!

I'm trying to implement vue-zoomer in a project and it works flawlessly on desktop. On mobile devices on the other hand, pinch zoom causes the browser to zoom in, instead of the image in the vue-zoomer.

I have created a sandbox where I tried to replicate your "Single image" [demo ](https://github.com/jarvisniu/vue-zoomer/tree/master/demo/basic) and I get the same behaviour. [Link to sandbox](https://codesandbox.io/s/exciting-saha-3ivtp)

Follow up question:
Is "user-scalable=no" required in the meta tag for this to work?

**Comment by jarvisniu** [comment]
Yes,

```html
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
```

is must have if you want to use it on mobile devices.

But nowadays, some browser will still ignore this. Like mobile safari will ignore it if your page contains a `font-size < 16px`.

I don't know if there are other reasons that mobile safari will do it.

If you find your answer, you can write it here. Other developers and i will be very thankful!
