### ISSUE TITLE
How to call the reset method?

### ISSUE THREAD

**Issue by biroa** [jarvisniu/vue-zoomer#36]
@Hi,
I set up the plugin in vue3 without any problem but I haven't found any details in the spec about the reset method. How can I call it? I am using v-zoomer feature only and I need to reset the magnification. Thanks the info!

**Comment by biroa** [comment]
> @hi, I set up the plugin in vue3 without any problem but I haven't found any details in the spec about the reset method. How can I call it? I am using v-zoomer feature only and I need to reset the magnification. Thanks the info!

I could call this way but nothing happens. The magnigication is sill the same.
VueZoomer.Zoomer.methods.reset(); 
Any idea how could I force reset on mouseout or mouseleave?

Thank you!

**Comment by jarvisniu** [comment]
https://vuejs.org/guide/essentials/template-refs.html
