### ISSUE TITLE
Not working when running nuxt generate

### ISSUE THREAD

**Issue by UIX-Design** [jarvisniu/vue-zoomer#4]
@jarvisniu When i run, `nuxt generate` or `nuxt build && nuxt start` the `vue-zoomer-gallery` is not working. I can open the Gallery, but i can't swipe to switch between my images.

How can we solve the problem, so i can use the `vue-zoomer` component?

**Comment by jarvisniu** [comment]
I think it's caused by not setting the `width` and `height` style.
You must set the size to fixed or 100%. When you set `height: 100%`, you should set all its ancestor element to `100%` too.

**Comment by UIX-Design** [comment]
@jarvisniu i already set the width and height to 100%

I can open the Gallery, but i can‘t change the images. The Gallery always opens the image on index 0 of my array
