### ISSUE TITLE
Removing Double Click to Zoom

### ISSUE THREAD

**Issue by willsned** [jarvisniu/vue-zoomer#6]
Hi, I love this component, I'd just rather not have the ability to double click to zoom. I tried using refs to set tapDetector to null, and detaching the tapDetector, but neither of those work for me. Any thoughts? Thanks

**Comment by jarvisniu** [comment]
I have added a prop to do that.
Update to `v0.3.2` and set prop `:double-click-to-zoom="false"`.

**Comment by willsned** [comment]
Thanks, I appreciate it
