### ISSUE TITLE
[FEATURE REQUEST] Add a way so we can zoom in and out with buttons 

### ISSUE THREAD

**Issue by jloracudris** [jarvisniu/vue-zoomer#7]
Hey great work with this lib

It would be really cool if it can zoom in and out with buttons.

**Comment by jarvisniu** [comment]
Sorry for the delay.
I have added the method `zoomIn(scale=2)` and `zoomOut(scale=0.5)` to do that (update to `v0.3.3`).
You need to add the two buttons yourself. : )
